
export const allahNames = [
  {
    name: 'الرحمن',
    transliteration: 'Ar-Rahman',
    meaning: 'The Beneficent',
    kannada_meaning: 'ಪರಮ ದಯಾಮಯ',
  },
  {
    name: 'الرحيم',
    transliteration: 'Ar-Rahim',
    meaning: 'The Merciful',
    kannada_meaning: 'ಕರುಣಾಮಯಿ',
  },
  {
    name: 'الملك',
    transliteration: 'Al-Malik',
    meaning: 'The King',
    kannada_meaning: 'ರಾಜ',
  },
  {
    name: 'القدوس',
    transliteration: 'Al-Quddus',
    meaning: 'The Most Holy',
    kannada_meaning: 'ಪರಿಶುದ್ಧ',
  },
  {
    name: 'السلام',
    transliteration: 'As-Salam',
    meaning: 'The Source of Peace',
    kannada_meaning: 'ಶಾಂತಿದಾತ',
  },
  {
    name: 'المؤمن',
    transliteration: 'Al-Mu’min',
    meaning: 'The Guardian of Faith',
    kannada_meaning: 'ವಿಶ್ವಾಸದ ರಕ್ಷಕ',
  },
  {
    name: 'المهيمن',
    transliteration: 'Al-Muhaymin',
    meaning: 'The Protector',
    kannada_meaning: 'ರಕ್ಷಕ',
  },
  {
    name: 'العزيز',
    transliteration: 'Al-Aziz',
    meaning: 'The Mighty',
    kannada_meaning: 'ಸರ್ವಶಕ್ತ',
  },
  {
    name: 'الجبار',
    transliteration: 'Al-Jabbar',
    meaning: 'The Compeller',
    kannada_meaning: 'ಒತ್ತಾಯಿಸುವವ',
  },
  {
    name: 'المتكبر',
    transliteration: 'Al-Mutakabbir',
    meaning: 'The Majestic',
    kannada_meaning: 'ಮಹಿಮೆಯುಳ್ಳವ',
  },
  {
    name: 'الخالق',
    transliteration: 'Al-Khaliq',
    meaning: 'The Creator',
    kannada_meaning: 'ಸೃಷ್ಟಿಕರ್ತ',
  },
  {
    name: 'البارئ',
    transliteration: 'Al-Bari',
    meaning: 'The Evolver',
    kannada_meaning: 'ವಿಕಾಸಕ',
  },
  {
    name: 'المصور',
    transliteration: 'Al-Musawwir',
    meaning: 'The Fashioner',
    kannada_meaning: 'ರೂಪಿಸುವವ',
  },
  {
    name: 'الغفار',
    transliteration: 'Al-Ghaffar',
    meaning: 'The Great Forgiver',
    kannada_meaning: 'ಮಹಾ ಕ್ಷಮಿಸುವವ',
  },
  {
    name: 'القهار',
    transliteration: 'Al-Qahhar',
    meaning: 'The All-Prevailing',
    kannada_meaning: 'ಸರ್ವವ್ಯಾಪಿ',
  },
  {
    name: 'الوهاب',
    transliteration: 'Al-Wahhab',
    meaning: 'The Bestower',
    kannada_meaning: 'ದಾನಿ',
  },
  {
    name: 'الرزاق',
    transliteration: 'Ar-Razzaq',
    meaning: 'The Provider',
    kannada_meaning: 'ಪೂರೈಕೆದಾರ',
  },
  {
    name: 'الفتاح',
    transliteration: 'Al-Fattah',
    meaning: 'The Opener',
    kannada_meaning: 'ತೆರೆಯುವವ',
  },
  {
    name: 'العليم',
    transliteration: 'Al-Alim',
    meaning: 'The All-Knowing',
    kannada_meaning: 'ಸರ್ವಜ್ಞ',
  },
  {
    name: 'القابض',
    transliteration: 'Al-Qabid',
    meaning: 'The Restrainer',
    kannada_meaning: 'ತಡೆಯುವವ',
  },
  {
    name: 'الباسط',
    transliteration: 'Al-Basit',
    meaning: 'The Extender',
    kannada_meaning: 'ವಿಸ್ತರಿಸುವವ',
  },
  {
    name: 'الخافض',
    transliteration: 'Al-Khafid',
    meaning: 'The Abaser',
    kannada_meaning: 'ಅವಮಾನಿಸುವವ',
  },
  {
    name: 'الرافع',
    transliteration: 'Ar-Rafi',
    meaning: 'The Exalter',
    kannada_meaning: 'ಎತ್ತುವವ',
  },
  {
    name: 'المعز',
    transliteration: 'Al-Mu’izz',
    meaning: 'The Honorer',
    kannada_meaning: 'ಗೌರವಿಸುವವ',
  },
  {
    name: 'المذل',
    transliteration: 'Al-Mudhill',
    meaning: 'The Dishonorer',
    kannada_meaning: 'ಅಗೌರವಿಸುವವ',
  },
  {
    name: 'السميع',
    transliteration: 'As-Sami',
    meaning: 'The All-Hearing',
    kannada_meaning: 'ಸರ್ವ ಕೇಳುಗ',
  },
  {
    name: 'البصير',
    transliteration: 'Al-Basir',
    meaning: 'The All-Seeing',
    kannada_meaning: 'ಸರ್ವ ನೋಡುವವ',
  },
  { name: 'الحكم', transliteration: 'Al-Hakam', meaning: 'The Judge', kannada_meaning: 'ನ್ಯಾಯಾಧೀಶ' },
  {
    name: 'العدل',
    transliteration: 'Al-Adl',
    meaning: 'The Utterly Just',
    kannada_meaning: 'ಸಂಪೂರ್ಣ ನ್ಯಾಯವಂತ',
  },
  {
    name: 'اللطيف',
    transliteration: 'Al-Latif',
    meaning: 'The Subtle One',
    kannada_meaning: 'ಸೂಕ್ಷ್ಮವಾದವ',
  },
  {
    name: 'الخبير',
    transliteration: 'Al-Khabir',
    meaning: 'The All-Aware',
    kannada_meaning: 'ಸರ್ವಜ್ಞ',
  },
  {
    name: 'الحليم',
    transliteration: 'Al-Halim',
    meaning: 'The Forbearing',
    kannada_meaning: 'ಸಹನಾಶೀಲ',
  },
  {
    name: 'العظيم',
    transliteration: 'Al-Azim',
    meaning: 'The Magnificent',
    kannada_meaning: 'ಭವ್ಯವಾದವ',
  },
  {
    name: 'الغفور',
    transliteration: 'Al-Ghafur',
    meaning: 'The All-Forgiving',
    kannada_meaning: 'ಸರ್ವಕ್ಷಮ',
  },
  {
    name: 'الشكور',
    transliteration: 'Ash-Shakur',
    meaning: 'The Grateful',
    kannada_meaning: 'ಕೃತಜ್ಞ',
  },
  {
    name: 'العلي',
    transliteration: 'Al-Ali',
    meaning: 'The Most High',
    kannada_meaning: 'ಅತ್ಯುನ್ನತ',
  },
  { name: 'الكبير', transliteration: 'Al-Kabir', meaning: 'The Great', kannada_meaning: 'ಮಹಾನ್' },
  {
    name: 'الحفيظ',
    transliteration: 'Al-Hafiz',
    meaning: 'The Preserver',
    kannada_meaning: 'ಸಂರಕ್ಷಕ',
  },
  {
    name: 'المقيت',
    transliteration: 'Al-Muqit',
    meaning: 'The Sustainer',
    kannada_meaning: 'ಪೋಷಕ',
  },
  {
    name: 'الحسيب',
    transliteration: 'Al-Hasib',
    meaning: 'The Reckoner',
    kannada_meaning: 'ಲೆಕ್ಕ ಹಾಕುವವ',
  },
  {
    name: 'الجليل',
    transliteration: 'Al-Jalil',
    meaning: 'The Majestic',
    kannada_meaning: 'ಮಹಿಮೆಯುಳ್ಳವ',
  },
  {
    name: 'الكريم',
    transliteration: 'Al-Karim',
    meaning: 'The Bountiful',
    kannada_meaning: 'ಉದಾರಿ',
  },
  {
    name: 'الرقيب',
    transliteration: 'Ar-Raqib',
    meaning: 'The Watchful',
    kannada_meaning: 'ವೀಕ್ಷಕ',
  },
  {
    name: 'المجيب',
    transliteration: 'Al-Mujib',
    meaning: 'The Responsive',
    kannada_meaning: 'ಪ್ರತಿಕ್ರಿಯಿಸುವವ',
  },
  {
    name: 'الواسع',
    transliteration: 'Al-Wasi',
    meaning: 'The All-Encompassing',
    kannada_meaning: 'ಸರ್ವವ್ಯಾಪಿ',
  },
  { name: 'الحكيم', transliteration: 'Al-Hakim', meaning: 'The Wise', kannada_meaning: 'ಜ್ಞಾನಿ' },
  { name: 'الودود', transliteration: 'Al-Wadud', meaning: 'The Loving', kannada_meaning: 'ಪ್ರೀತಿಯುಳ್ಳವ' },
  {
    name: 'المجيد',
    transliteration: 'Al-Majid',
    meaning: 'The Glorious',
    kannada_meaning: 'ಮಹಿಮೆಯುಳ್ಳವ',
  },
  {
    name: 'الباعث',
    transliteration: 'Al-Ba’ith',
    meaning: 'The Resurrector',
    kannada_meaning: 'ಪುನರುತ್ಥಾನಗೊಳಿಸುವವ',
  },
  { name: 'الشهيد', transliteration: 'Ash-Shahid', meaning: 'The Witness', kannada_meaning: 'ಸಾಕ್ಷಿ' },
  { name: 'الحق', transliteration: 'Al-Haqq', meaning: 'The Truth', kannada_meaning: 'ಸತ್ಯ' },
  {
    name: 'الوكيل',
    transliteration: 'Al-Wakil',
    meaning: 'The Trustee',
    kannada_meaning: 'ನಂಬಿಗಸ್ತ',
  },
  { name: 'القوي', transliteration: 'Al-Qawiyy', meaning: 'The Strong', kannada_meaning: 'ಬಲಶಾಲಿ' },
  { name: 'المتين', transliteration: 'Al-Matin', meaning: 'The Firm One', kannada_meaning: 'ದೃಢವಾದವ' },
  {
    name: 'الولي',
    transliteration: 'Al-Waliyy',
    meaning: 'The Protecting Friend',
    kannada_meaning: 'ರಕ್ಷಕ ಮಿತ್ರ',
  },
  {
    name: 'الحميد',
    transliteration: 'Al-Hamid',
    meaning: 'The Praiseworthy',
    kannada_meaning: 'ಹೊಗಳಿಕೆಗೆ ಪಾತ್ರ',
  },
  {
    name: 'المحصي',
    transliteration: 'Al-Muhsi',
    meaning: 'The Accounter',
    kannada_meaning: 'ಲೆಕ್ಕ ಇಡುವವ',
  },
  {
    name: 'المبدئ',
    transliteration: 'Al-Mubdi',
    meaning: 'The Originator',
    kannada_meaning: 'ಮೂಲಕಾರಣ',
  },
  {
    name: 'المعيد',
    transliteration: 'Al-Mu’id',
    meaning: 'The Restorer',
    kannada_meaning: 'ಪುನಃಸ್ಥಾಪಕ',
  },
  {
    name: 'المحيي',
    transliteration: 'Al-Muhyi',
    meaning: 'The Giver of Life',
    kannada_meaning: 'ಜೀವದಾತ',
  },
  {
    name: 'المميت',
    transliteration: 'Al-Mumit',
    meaning: 'The Taker of Life',
    kannada_meaning: 'ಜೀವ ತೆಗೆಯುವವ',
  },
  {
    name: 'الحي',
    transliteration: 'Al-Hayy',
    meaning: 'The Ever-Living',
    kannada_meaning: 'ಚಿರಂಜೀವಿ',
  },
  {
    name: 'القيوم',
    transliteration: 'Al-Qayyum',
    meaning: 'The Self-Existing',
    kannada_meaning: 'ಸ್ವಯಂ ಅಸ್ತಿತ್ವ',
  },
  {
    name: 'الواجد',
    transliteration: 'Al-Wajid',
    meaning: 'The Perceiver',
    kannada_meaning: 'ಗ್ರಹಿಸುವವ',
  },
  {
    name: 'الماجد',
    transliteration: 'Al-Majid',
    meaning: 'The Illustrious',
    kannada_meaning: 'ಪ್ರಖ್ಯಾತ',
  },
  { name: 'الواحد', transliteration: 'Al-Wahid', meaning: 'The One', kannada_meaning: 'ಏಕ' },
  { name: 'الاحد', transliteration: 'Al-Ahad', meaning: 'The Unique', kannada_meaning: 'ಅನನ್ಯ' },
  { name: 'الصمد', transliteration: 'As-Samad', meaning: 'The Eternal', kannada_meaning: 'ಶಾಶ್ವತ' },
  { name: 'القادر', transliteration: 'Al-Qadir', meaning: 'The Able', kannada_meaning: 'ಸಮರ್ಥ' },
  {
    name: 'المقتدر',
    transliteration: 'Al-Muqtadir',
    meaning: 'The All-Determiner',
    kannada_meaning: 'ಸರ್ವ-ನಿರ್ಧಾರಕ',
  },
  {
    name: 'المقدم',
    transliteration: 'Al-Muqaddim',
    meaning: 'The Expediter',
    kannada_meaning: 'ಮುಂದೂಡುವವ',
  },
  {
    name: 'المؤخر',
    transliteration: 'Al-Mu’akhkhir',
    meaning: 'The Delayer',
    kannada_meaning: 'ವಿಳಂಬಿಸುವವ',
  },
  { name: 'الأول', transliteration: 'Al-Awwal', meaning: 'The First', kannada_meaning: 'ಪ್ರಥಮ' },
  { name: 'الآخر', transliteration: 'Al-Akhir', meaning: 'The Last', kannada_meaning: 'ಅಂತಿಮ' },
  {
    name: 'الظاهر',
    transliteration: 'Az-Zahir',
    meaning: 'The Manifest',
    kannada_meaning: 'ಪ್ರಕಟ',
  },
  { name: 'الباطن', transliteration: 'Al-Batin', meaning: 'The Hidden', kannada_meaning: 'ಗುಪ್ತ' },
  {
    name: 'الوالي',
    transliteration: 'Al-Wali',
    meaning: 'The Governor',
    kannada_meaning: 'ರಾಜ್ಯಪಾಲ',
  },
  {
    name: 'المتعالي',
    transliteration: 'Al-Muta’ali',
    meaning: 'The Most Exalted',
    kannada_meaning: 'ಅತ್ಯುನ್ನತ',
  },
  {
    name: 'البر',
    transliteration: 'Al-Barr',
    meaning: 'The Source of All-Goodness',
    kannada_meaning: 'ಒಳಿತಿನ ಮೂಲ',
  },
  {
    name: 'التواب',
    transliteration: 'At-Tawwab',
    meaning: 'The Acceptor of Repentance',
    kannada_meaning: 'ಪಶ್ಚಾತ್ತಾಪ ಸ್ವೀಕರಿಸುವವ',
  },
  {
    name: 'المنتقم',
    transliteration: 'Al-Muntaqim',
    meaning: 'The Avenger',
    kannada_meaning: 'ಪ್ರತೀಕಾರ ತೀರಿಸುವವ',
  },
  { name: 'العفو', transliteration: 'Al-Afuww', meaning: 'The Pardoner', kannada_meaning: 'ಕ್ಷಮಿಸುವವ' },
  {
    name: 'الرؤوف',
    transliteration: 'Ar-Ra’uf',
    meaning: 'The Compassionate',
    kannada_meaning: 'ಕರುಣಾಮಯಿ',
  },
  {
    name: 'مالك الملك',
    transliteration: 'Malik-al-Mulk',
    meaning: 'The Owner of Sovereignty',
    kannada_meaning: 'ಸಾರ್ವಭೌಮತ್ವದ ಒಡೆಯ',
  },
  {
    name: 'ذو الجلال والإكرام',
    transliteration: 'Dhul-Jalal wal-Ikram',
    meaning: 'The Lord of Majesty and Bounty',
    kannada_meaning: 'ಮಹಿಮೆ ಮತ್ತು ಔದಾರ್ಯದ ಪ್ರಭು',
  },
  {
    name: 'المقسط',
    transliteration: 'Al-Muqsit',
    meaning: 'The Equitable',
    kannada_meaning: 'ನ್ಯಾಯವಂತ',
  },
  {
    name: 'الجامع',
    transliteration: 'Al-Jami',
    meaning: 'The Gatherer',
    kannada_meaning: 'ಸಂಗ್ರಹಕಾರ',
  },
  {
    name: 'الغني',
    transliteration: 'Al-Ghani',
    meaning: 'The Self-Sufficient',
    kannada_meaning: 'ಸ್ವಾವಲಂಬಿ',
  },
  {
    name: 'المغني',
    transliteration: 'Al-Mughni',
    meaning: 'The Enricher',
    kannada_meaning: 'ಸಮೃದ್ಧಗೊಳಿಸುವವ',
  },
  {
    name: 'المانع',
    transliteration: 'Al-Mani',
    meaning: 'The Withholder',
    kannada_meaning: 'ತಡೆಯುವವ',
  },
  {
    name: 'الضار',
    transliteration: 'Ad-Darr',
    meaning: 'The Distresser',
    kannada_meaning: 'ಸಂಕಟ ಕೊಡುವವ',
  },
  {
    name: 'النافع',
    transliteration: 'An-Nafi',
    meaning: 'The Propitious',
    kannada_meaning: 'ಶುಭಕರ',
  },
  { name: 'النور', transliteration: 'An-Nur', meaning: 'The Light', kannada_meaning: 'ಬೆಳಕು' },
  { name: 'الهادي', transliteration: 'Al-Hadi', meaning: 'The Guide', kannada_meaning: 'ಮಾರ್ಗದರ್ಶಕ' },
  {
    name: 'البديع',
    transliteration: 'Al-Badi',
    meaning: 'The Incomparable',
    kannada_meaning: 'ಅಸದೃಶ',
  },
  {
    name: 'الباقي',
    transliteration: 'Al-Baqi',
    meaning: 'The Everlasting',
    kannada_meaning: 'ಶಾಶ್ವತ',
  },
  {
    name: 'الوارث',
    transliteration: 'Al-Warith',
    meaning: 'The Supreme Inheritor',
    kannada_meaning: 'ಪರಮ ಉತ್ತರಾಧಿಕಾರಿ',
  },
  {
    name: 'الرشيد',
    transliteration: 'Ar-Rashid',
    meaning: 'The Guide to the Right Path',
    kannada_meaning: 'ಸರಿಯಾದ ಮಾರ್ಗದರ್ಶಕ',
  },
  {
    name: 'الصبور',
    transliteration: 'As-Sabur',
    meaning: 'The Patient',
    kannada_meaning: 'ಸಹನಾಶೀಲ',
  },
];

    