export const allahNames = [
  {
    name: 'الرحمن',
    transliteration: 'Ar-Rahman',
    meaning: 'The Beneficent',
  },
  { name: 'الرحيم', transliteration: 'Ar-Rahim', meaning: 'The Merciful' },
  { name: 'الملك', transliteration: 'Al-Malik', meaning: 'The King' },
  { name: 'القدوس', transliteration: 'Al-Quddus', meaning: 'The Most Holy' },
  { name: 'السلام', transliteration: 'As-Salam', meaning: 'The Source of Peace' },
  {
    name: 'المؤمن',
    transliteration: 'Al-Mu’min',
    meaning: 'The Guardian of Faith',
  },
  {
    name: 'المهيمن',
    transliteration: 'Al-Muhaymin',
    meaning: 'The Protector',
  },
  { name: 'العزيز', transliteration: 'Al-Aziz', meaning: 'The Mighty' },
  { name: 'الجبار', transliteration: 'Al-Jabbar', meaning: 'The Compeller' },
  {
    name: 'المتكبر',
    transliteration: 'Al-Mutakabbir',
    meaning: 'The Majestic',
  },
  { name: 'الخالق', transliteration: 'Al-Khaliq', meaning: 'The Creator' },
  { name: 'البارئ', transliteration: 'Al-Bari', meaning: 'The Evolver' },
  {
    name: 'المصور',
    transliteration: 'Al-Musawwir',
    meaning: 'The Fashioner',
  },
  { name: 'الغفار', transliteration: 'Al-Ghaffar', meaning: 'The Great Forgiver' },
  { name: 'القهار', transliteration: 'Al-Qahhar', meaning: 'The All-Prevailing' },
  { name: 'الوهاب', transliteration: 'Al-Wahhab', meaning: 'The Bestower' },
  { name: 'الرزاق', transliteration: 'Ar-Razzaq', meaning: 'The Provider' },
  { name: 'الفتاح', transliteration: 'Al-Fattah', meaning: 'The Opener' },
  { name: 'العليم', transliteration: 'Al-Alim', meaning: 'The All-Knowing' },
  { name: 'القابض', transliteration: 'Al-Qabid', meaning: 'The Restrainer' },
  { name: 'الباسط', transliteration: 'Al-Basit', meaning: 'The Extender' },
  { name: 'الخافض', transliteration: 'Al-Khafid', meaning: 'The Abaser' },
  { name: 'الرافع', transliteration: 'Ar-Rafi', meaning: 'The Exalter' },
  { name: 'المعز', transliteration: 'Al-Mu’izz', meaning: 'The Honorer' },
  { name: 'المذل', transliteration: 'Al-Mudhill', meaning: 'The Dishonorer' },
  { name: 'السميع', transliteration: 'As-Sami', meaning: 'The All-Hearing' },
  { name: 'البصير', transliteration: 'Al-Basir', meaning: 'The All-Seeing' },
  { name: 'الحكم', transliteration: 'Al-Hakam', meaning: 'The Judge' },
  { name: 'العدل', transliteration: 'Al-Adl', meaning: 'The Utterly Just' },
  { name: 'اللطيف', transliteration: 'Al-Latif', meaning: 'The Subtle One' },
  { name: 'الخبير', transliteration: 'Al-Khabir', meaning: 'The All-Aware' },
  { name: 'الحليم', transliteration: 'Al-Halim', meaning: 'The Forbearing' },
  { name: 'العظيم', transliteration: 'Al-Azim', meaning: 'The Magnificent' },
  { name: 'الغفور', transliteration: 'Al-Ghafur', meaning: 'The All-Forgiving' },
  { name: 'الشكور', transliteration: 'Ash-Shakur', meaning: 'The Grateful' },
  { name: 'العلي', transliteration: 'Al-Ali', meaning: 'The Most High' },
  { name: 'الكبير', transliteration: 'Al-Kabir', meaning: 'The Great' },
  { name: 'الحفيظ', transliteration: 'Al-Hafiz', meaning: 'The Preserver' },
  { name: 'المقيت', transliteration: 'Al-Muqit', meaning: 'The Sustainer' },
  { name: 'الحسيب', transliteration: 'Al-Hasib', meaning: 'The Reckoner' },
  { name: 'الجليل', transliteration: 'Al-Jalil', meaning: 'The Majestic' },
  { name: 'الكريم', transliteration: 'Al-Karim', meaning: 'The Bountiful' },
  { name: 'الرقيب', transliteration: 'Ar-Raqib', meaning: 'The Watchful' },
  { name: 'المجيب', transliteration: 'Al-Mujib', meaning: 'The Responsive' },
  { name: 'الواسع', transliteration: 'Al-Wasi', meaning: 'The All-Encompassing' },
  { name: 'الحكيم', transliteration: 'Al-Hakim', meaning: 'The Wise' },
  { name: 'الودود', transliteration: 'Al-Wadud', meaning: 'The Loving' },
  { name: 'المجيد', transliteration: 'Al-Majid', meaning: 'The Glorious' },
  { name: 'الباعث', transliteration: 'Al-Ba’ith', meaning: 'The Resurrector' },
  { name: 'الشهيد', transliteration: 'Ash-Shahid', meaning: 'The Witness' },
  { name: 'الحق', transliteration: 'Al-Haqq', meaning: 'The Truth' },
  { name: 'الوكيل', transliteration: 'Al-Wakil', meaning: 'The Trustee' },
  { name: 'القوي', transliteration: 'Al-Qawiyy', meaning: 'The Strong' },
  { name: 'المتين', transliteration: 'Al-Matin', meaning: 'The Firm One' },
  { name: 'الولي', transliteration: 'Al-Waliyy', meaning: 'The Protecting Friend' },
  { name: 'الحميد', transliteration: 'Al-Hamid', meaning: 'The Praiseworthy' },
  { name: 'المحصي', transliteration: 'Al-Muhsi', meaning: 'The Accounter' },
  { name: 'المبدئ', transliteration: 'Al-Mubdi', meaning: 'The Originator' },
  { name: 'المعيد', transliteration: 'Al-Mu’id', meaning: 'The Restorer' },
  { name: 'المحيي', transliteration: 'Al-Muhyi', meaning: 'The Giver of Life' },
  { name: 'المميت', transliteration: 'Al-Mumit', meaning: 'The Taker of Life' },
  { name: 'الحي', transliteration: 'Al-Hayy', meaning: 'The Ever-Living' },
  { name: 'القيوم', transliteration: 'Al-Qayyum', meaning: 'The Self-Existing' },
  { name: 'الواجد', transliteration: 'Al-Wajid', meaning: 'The Perceiver' },
  { name: 'الماجد', transliteration: 'Al-Majid', meaning: 'The Illustrious' },
  { name: 'الواحد', transliteration: 'Al-Wahid', meaning: 'The One' },
  { name: 'الاحد', transliteration: 'Al-Ahad', meaning: 'The Unique' },
  { name: 'الصمد', transliteration: 'As-Samad', meaning: 'The Eternal' },
  { name: 'القادر', transliteration: 'Al-Qadir', meaning: 'The Able' },
  {
    name: 'المقتدر',
    transliteration: 'Al-Muqtadir',
    meaning: 'The All-Determiner',
  },
  { name: 'المقدم', transliteration: 'Al-Muqaddim', meaning: 'The Expediter' },
  { name: 'المؤخر', transliteration: 'Al-Mu’akhkhir', meaning: 'The Delayer' },
  { name: 'الأول', transliteration: 'Al-Awwal', meaning: 'The First' },
  { name: 'الآخر', transliteration: 'Al-Akhir', meaning: 'The Last' },
  { name: 'الظاهر', transliteration: 'Az-Zahir', meaning: 'The Manifest' },
  { name: 'الباطن', transliteration: 'Al-Batin', meaning: 'The Hidden' },
  { name: 'الوالي', transliteration: 'Al-Wali', meaning: 'The Governor' },
  { name: 'المتعالي', transliteration: 'Al-Muta’ali', meaning: 'The Most Exalted' },
  { name: 'البر', transliteration: 'Al-Barr', meaning: 'The Source of All-Goodness' },
  { name: 'التواب', transliteration: 'At-Tawwab', meaning: 'The Acceptor of Repentance' },
  { name: 'المنتقم', transliteration: 'Al-Muntaqim', meaning: 'The Avenger' },
  { name: 'العفو', transliteration: 'Al-Afuww', meaning: 'The Pardoner' },
  { name: 'الرؤوف', transliteration: 'Ar-Ra’uf', meaning: 'The Compassionate' },
  {
    name: 'مالك الملك',
    transliteration: 'Malik-al-Mulk',
    meaning: 'The Owner of Sovereignty',
  },
  {
    name: 'ذو الجلال والإكرام',
    transliteration: 'Dhul-Jalal wal-Ikram',
    meaning: 'The Lord of Majesty and Bounty',
  },
  { name: 'المقسط', transliteration: 'Al-Muqsit', meaning: 'The Equitable' },
  { name: 'الجامع', transliteration: 'Al-Jami', meaning: 'The Gatherer' },
  { name: 'الغني', transliteration: 'Al-Ghani', meaning: 'The Self-Sufficient' },
  { name: 'المغني', transliteration: 'Al-Mughni', meaning: 'The Enricher' },
  { name: 'المانع', transliteration: 'Al-Mani', meaning: 'The Withholder' },
  { name: 'الضار', transliteration: 'Ad-Darr', meaning: 'The Distresser' },
  { name: 'النافع', transliteration: 'An-Nafi', meaning: 'The Propitious' },
  { name: 'النور', transliteration: 'An-Nur', meaning: 'The Light' },
  { name: 'الهادي', transliteration: 'Al-Hadi', meaning: 'The Guide' },
  { name: 'البديع', transliteration: 'Al-Badi', meaning: 'The Incomparable' },
  { name: 'الباقي', transliteration: 'Al-Baqi', meaning: 'The Everlasting' },
  { name: 'الوارث', transliteration: 'Al-Warith', meaning: 'The Supreme Inheritor' },
  { name: 'الرشيد', transliteration: 'Ar-Rashid', meaning: 'The Guide to the Right Path' },
  { name: 'الصبور', transliteration: 'As-Sabur', meaning: 'The Patient' },
];
