export const hadisData = [
  {
    arabic: 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ',
    transliteration: 'Innamal a\'maalu bin-niyyaat',
    translation: 'Verily, actions are but by intentions.',
    reference: 'Sahih al-Bukhari 1',
  },
  {
    arabic: 'الدِّينُ النَّصِيحَةُ',
    transliteration: 'Ad-deenu an-naseeha',
    translation: 'The religion is advice.',
    reference: 'Sahih Muslim 55',
  },
  {
    arabic: 'لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
    transliteration: 'La yu\'minu ahadukum hatta yuhibba li akhihi ma yuhibbu li nafsihi',
    translation: 'None of you truly believes until he loves for his brother what he loves for himself.',
    reference: 'Sahih al-Bukhari 13',
  },
  {
    arabic: 'مَنْ غَشَّنَا فَلَيْسَ مِنَّا',
    transliteration: 'Man ghash-shanaa fa laysa minnaa',
    translation: 'Whoever deceives us is not one of us.',
    reference: 'Sahih Muslim 101',
  },
  {
    arabic: 'الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ',
    transliteration: 'Al-muslimu man salima al-muslimoona min lisaanihi wa yadihi',
    translation: 'The Muslim is the one from whose tongue and hand the Muslims are safe.',
    reference: 'Sahih al-Bukhari 10',
  },
  {
    arabic: 'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ',
    transliteration: 'Khayrukum man ta\'allamal-qur\'aana wa \'allamahu',
    translation: 'The best of you are those who learn the Quran and teach it.',
    reference: 'Sahih al-Bukhari 5027',
  },
  {
    arabic: 'الطَّهُورُ شَطْرُ الْإِيمَانِ',
    transliteration: 'At-tahooru shatrul-eemaan',
    translation: 'Purity is half of faith.',
    reference: 'Sahih Muslim 223',
  },
  {
    arabic: 'مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ',
    transliteration: 'Man yuridillahu bihi khairan yufaqqihhu fid-deen',
    translation: 'Whomever Allah wishes good for, He gives him understanding of the religion.',
    reference: 'Sahih al-Bukhari 71',
  },
  {
    arabic: 'إِذَا مَاتَ الْإِنْسَانُ انْقَطَعَ عَنْهُ عَمَلُهُ إِلَّا مِنْ ثَلَاثَةٍ',
    transliteration: 'Idha maatal-insanu inqata\'a \'anhu \'amaluhu illa min thalaathah',
    translation: 'When a person dies, his deeds come to an end except for three.',
    reference: 'Sahih Muslim 1631',
  },
  {
    arabic: 'اِتَّقِ اللَّهَ حَيْثُمَا كُنْتَ',
    transliteration: 'Ittaqillaaha haythu maa kunta',
    translation: 'Fear Allah wherever you are.',
    reference: 'Jami` at-Tirmidhi 1987',
  },
  {
    arabic: 'الْحَيَاءُ مِنَ الإِيمَانِ',
    transliteration: 'Al-hayaa\'u minal-eemaan',
    translation: 'Modesty is part of faith.',
    reference: 'Sahih al-Bukhari 24',
  },
  {
    arabic: 'مَنْ صَمَتَ نَجَا',
    transliteration: 'Man samata najaa',
    translation: 'Whoever is silent, is saved.',
    reference: 'Jami` at-Tirmidhi 2501',
  },
  {
    arabic: 'لاَ ضَرَرَ وَلاَ ضِرَارَ',
    transliteration: 'Laa darara wa laa diraar',
    translation: 'There should be neither harming nor reciprocating harm.',
    reference: 'Sunan Ibn Majah 2341',
  },
  {
    arabic: 'الْيَدُ الْعُلْيَا خَيْرٌ مِنَ الْيَدِ السُّفْلَى',
    transliteration: 'Al-yadul-\'ulya khayrun minal-yadis-sufla',
    translation: 'The upper hand is better than the lower hand.',
    reference: 'Sahih al-Bukhari 1429',
  },
  {
    arabic: 'كُلُّ مَعْرُوفٍ صَدَقَةٌ',
    transliteration: 'Kullu ma\'roofin sadaqah',
    translation: 'Every good deed is a charity.',
    reference: 'Sahih al-Bukhari 6021',
  },
  {
    arabic: 'الْكَلِمَةُ الطَّيِّبَةُ صَدَقَةٌ',
    transliteration: 'Al-kalimatut-tayyibatu sadaqah',
    translation: 'A good word is a charity.',
    reference: 'Sahih al-Bukhari 6023',
  },
  {
    arabic: 'أَحَبُّ الأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ',
    transliteration: 'Ahab-bul a\'maali ilallahi adwamuha wa in qalla',
    translation: 'The most beloved of deeds to Allah are the most consistent of them, even if they are few.',
    reference: 'Sahih al-Bukhari 6464',
  },
  {
    arabic: 'تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ',
    transliteration: 'Tabassumuka fee wajhi akheeka laka sadaqah',
    translation: 'Your smiling in the face of your brother is a charity.',
    reference: 'Jami` at-Tirmidhi 1956',
  },
  {
    arabic: 'إِنَّ اللَّهَ لاَ يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ',
    transliteration: 'Innallaaha laa yandhuru ilaa suwarikum wa amwaalikum, wa laakin yandhuru ilaa quloobikum wa a\'maalikum',
    translation: 'Verily, Allah does not look at your appearances or your wealth, but He looks at your hearts and your deeds.',
    reference: 'Sahih Muslim 2564c',
  },
  {
    arabic: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ',
    transliteration: 'Man salaka tareeqan yaltamisu feehi \'ilman sahhalallaahu lahu bihi tareeqan ilal-jannah',
    translation: 'Whoever travels a path in search of knowledge, Allah makes easy for him a path to Paradise.',
    reference: 'Sahih Muslim 2699',
  },
  {
    arabic: 'لاَ يَدْخُلُ الْجَنَّةَ قَاطِعٌ',
    transliteration: 'Laa yadkhulul-jannata qaati\'',
    translation: 'The one who severs ties of kinship will not enter Paradise.',
    reference: 'Sahih al-Bukhari 5984',
  },
  {
    arabic: 'إِنَّ الصِّدْقَ يَهْدِي إِلَى الْبِرِّ وَإِنَّ الْبِرَّ يَهْدِي إِلَى الْجَنَّةِ',
    transliteration: 'Innas-sidqa yahdee ilal-birri, wa innal-birra yahdee ilal-jannah',
    translation: 'Verily, truthfulness leads to righteousness, and righteousness leads to Paradise.',
    reference: 'Sahih al-Bukhari 6094',
  },
  {
    arabic: 'لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ، إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ',
    transliteration: 'Laysash-shadeedu bis-sura\'ati, innamash-shadeedul-ladhee yamliku nafsahu \'indal-ghadab',
    translation: 'The strong is not the one who overcomes the people by his strength, but the strong is the one who controls himself while in anger.',
    reference: 'Sahih al-Bukhari 6114',
  },
  {
    arabic: 'ارْحَمُوا مَنْ فِي الأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ',
    transliteration: 'Irhamoo man fil-ardi yarhamkum man fis-samaa\'',
    translation: 'Be merciful to those on the earth, and the One in the heavens will have mercy upon you.',
    reference: 'Jami` at-Tirmidhi 1924',
  },
  {
    arabic: 'مَنْ لَا يَرْحَمِ النَّاسَ لَا يَرْحَمْهُ اللَّهُ',
    transliteration: 'Man laa yarhamin-naasa laa yarhamhullaah',
    translation: 'He who does not show mercy to people, Allah will not show mercy to him.',
    reference: 'Sahih al-Bukhari 7376',
  },
  {
    arabic: 'أَكْمَلُ الْمُؤْمِنِينَ إِيمَانًا أَحْسَنُهُمْ خُلُقًا',
    transliteration: 'Akmulul-mu\'mineena eemaanan ahsanuhum khuluqan',
    translation: 'The most complete of the believers in faith are those with the best character.',
    reference: 'Jami` at-Tirmidhi 1162',
  },
  {
    arabic: 'الْبَخِيلُ مَنْ ذُكِرْتُ عِنْدَهُ فَلَمْ يُصَلِّ عَلَىَّ',
    transliteration: 'Al-bakheelu man dhukirtu \'indahu fa-lam yusalli \'alayya',
    translation: 'The miser is the one in whose presence I am mentioned but he does not send blessings upon me.',
    reference: 'Jami` at-Tirmidhi 3546',
  },
  {
    arabic: 'إِذَا اسْتَعَنْتَ فَاسْتَعِنْ بِاللَّهِ',
    transliteration: 'Idhas-ta\'anta fasta\'in billaah',
    translation: 'If you seek help, seek help from Allah.',
    reference: 'Jami` at-Tirmidhi 2516',
  },
  {
    arabic: 'احْفَظِ اللَّهَ يَحْفَظْكَ',
    transliteration: 'Ihfaz-illaaha yahfaz-ka',
    translation: 'Be mindful of Allah, and Allah will protect you.',
    reference: 'Jami` at-Tirmidhi 2516',
  },
  {
    arabic: 'إِنَّ اللَّهَ يُحِبُّ الْعَبْدَ التَّقِيَّ الْغَنِيَّ الْخَفِيَّ',
    transliteration: 'Innallaaha yuhibbul-\'abdat-taqiyyal-ghaniyyal-khafiyy',
    translation: 'Verily, Allah loves the servant who is pious, self-sufficient, and inconspicuous.',
    reference: 'Sahih Muslim 2965',
  },
  {
    arabic: 'قُلْ آمَنْتُ بِاللَّهِ ثُمَّ اسْتَقِمْ',
    transliteration: 'Qul aamantu billaahi thummas-taqim',
    translation: 'Say, "I believe in Allah," and then be steadfast.',
    reference: 'Sahih Muslim 38',
  },
  {
    arabic: 'مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ',
    transliteration: 'Maa naqasat sadaqatun min maal',
    translation: 'Charity does not decrease wealth.',
    reference: 'Sahih Muslim 2588',
  },
  {
    arabic: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
    transliteration: 'Man kaana yu\'minu billaahi wal-yawmil-aakhiri fal-yaqul khayran aw liyasmut',
    translation: 'Whoever believes in Allah and the Last Day, let him speak good or remain silent.',
    reference: 'Sahih al-Bukhari 6018',
  },
  {
    arabic: 'الْجَنَّةُ تَحْتَ أَقْدَامِ الأُمَّهَاتِ',
    transliteration: 'Al-jannatu tahta aqdaamil-ummahaat',
    translation: 'Paradise lies under the feet of mothers.',
    reference: 'Musnad Ahmad 15578',
  },
  {
    arabic: 'لاَ يَدْخُلُ الْجَنَّةَ نَمَّامٌ',
    transliteration: 'Laa yadkhulul-jannata nammaam',
    translation: 'A talebearer will not enter Paradise.',
    reference: 'Sahih al-Bukhari 6056',
  },
  {
    arabic: 'الدُّنْيَا سِجْنُ الْمُؤْمِنِ وَجَنَّةُ الْكَافِرِ',
    transliteration: 'Ad-dunya sijnul-mu\'mini wa jannatul-kaafir',
    translation: 'The world is a prison for the believer and a paradise for the disbeliever.',
    reference: 'Sahih Muslim 2956',
  },
  {
    arabic: 'مَنْ تَشَبَّهَ بِقَوْمٍ فَهُوَ مِنْهُمْ',
    transliteration: 'Man tashabbaha bi-qawmin fa huwa minhum',
    translation: 'Whoever imitates a people is one of them.',
    reference: 'Sunan Abi Dawud 4031',
  },
  {
    arabic: 'الرَّجُلُ عَلَى دِينِ خَلِيلِهِ فَلْيَنْظُرْ أَحَدُكُمْ مَنْ يُخَالِلُ',
    transliteration: 'Ar-rajulu \'alaa deeni khaleelihi fal-yanzur ahadukum man yukhaalil',
    translation: 'A man is upon the religion of his best friend, so let one of you look at whom he befriends.',
    reference: 'Jami` at-Tirmidhi 2378',
  },
  {
    arabic: 'إِنَّ اللَّهَ جَمِيلٌ يُحِبُّ الْجَمَالَ',
    transliteration: 'Innallaaha jameelun yuhibbul-jamaal',
    translation: 'Verily, Allah is beautiful and He loves beauty.',
    reference: 'Sahih Muslim 91',
  },
  {
    arabic: 'أَفْضَلُ الْجِهَادِ كَلِمَةُ عَدْلٍ عِنْدَ سُلْطَانٍ جَائِرٍ',
    transliteration: 'Afdalul-jihaadi kalimatu \'adlin \'inda sultaanin jaa\'ir',
    translation: 'The best jihad is a word of justice in front of a tyrannical ruler.',
    reference: 'Jami` at-Tirmidhi 2174',
  },
];
